# Define a Kubernetes Deployment for the backend application

apiVersion: apps/v1
kind: Deployment # Name of the Deployment
metadata:
  name: bgr-backend
spec:
  replicas: 1 # Number of replicas for high availability (adjust as needed)
  selector:
    matchLabels:
      app: bgr-backend # Label selector for identifying pods managed by this Deployment
  template:
    metadata:
      labels:
        app: bgr-backend # Labels to apply to pods created by this template
    spec:
      containers:
      - name: bgr-backend # Name of the container
        image: rishabh20539011/custom_bgr:backend  # Docker image for the container
        ports:
        - containerPort: 8000 # Port to expose on the container
