version: '3'

services:
  backend:
    build:
      context: ./path/to/backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    container_name: backend-container

  frontend:
    build:
      context: ./path/to/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    container_name: frontend-container

networks:
  app-network:
    driver: bridge
