version: '3.8'

services:
  bgr_frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    networks:
      - bgr_network

  bgr_backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    networks:
      - bgr_network

networks:
  bgr_network:
    driver: bridge

