# Define a Kubernetes Deployment for the frontend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgr-frontend # Name of the Deployment
spec:
  replicas: 1 # Number of replicas for high availability (adjust as needed)
  selector:
    matchLabels:
      app: bgr-frontend # Label selector for identifying pods managed by this Deployment
  template:
    metadata:
      labels:
        app: bgr-frontend # Labels to apply to pods created by this template
    spec:
      containers:
      - name: bgr-frontend # Name of the container
        image: rishabh20539011/custom_bgr:frontend # Docker image for the container
        ports:
        - containerPort: 3000 # Port to expose on the container