name: Deploy to GKE

on:
  workflow_run:
    workflows: ["Docker images"]
    types:
      - completed
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Configure Docker
      run: |
        docker login -u rishabh20539011 -p ${{ secrets.DOCKER_HUB_PASS }}

    - name: Pull Docker Image
      run: |
        docker pull your-docker-image

    - name: Connect to GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --zone asia-south2 --project ${{ secrets.PROJECT_ID }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f backend_deployment.yaml
        kubectl apply -f frontend_deployment.yaml
        kubectl apply -f backend_services.yaml
        kubectl apply -f frontend_services.yaml
        
