name: Check test cases
on:
  push:
    branches: [ temp ]
  pull_request:
    branches: [ temp ]
    
jobs:
  test_package:
    strategy:
      matrix:
        python-version: [3.10.4]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip3 install --no-cache-dir -r requirements.txt

    # - name: Download all models
    #   run: |
    #     python3 -c "from custom_bgr.project.ml_pipeline.models.file_location import download_all; download_all();"

    - name: Test with pytest
      run: |
        pytest -s -v

