name: Docker images

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Backend
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./
          file: "./Dockerfile.backend"
          tags: |
            rishabh20539011/custom_bgr:backend
      - name: Build and push Frontend
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./
          file: "./Dockerfile.frontend"
          tags: |
            rishabh20539011/custom_bgr:frontend
